version: '3.8'
services:
  dbmysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: mysql
    volumes:
      - ./data/mysql:/docker-entrypoint-initdb.d
    ports:
      - 8350:3306
    environment:
      MYSQL_ROOT_PASSWORD: ETxGkUcEZM7M22tP5
      MYSQL_DATABASE: api-template
  redis:
    image: redis
    container_name: cache
    ports:
      - 8353:6379
    expose:
      - 6379
  kafka:
    image: bitnami/kafka:3.5
    restart: always
    environment:
      KAFKA_BROKER_ID: "1"
      KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092"
      KAFKA_CFG_LOG_DIRS: "/bitnami/kafka/logs"
    ports:
      - 8354:9092
    depends_on:
      - zookeeper
  zookeeper:
    image: bitnami/zookeeper:3.8
    restart: always
    ports:
      - 8355:2181
volumes:
  db_data: { }
